server:
  servlet:
    context-path: /room-booking
  port: 9090

spring:
  application:
    name: room-booking
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:bookingDB;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

springdoc:
  swagger-ui:
    path: /api-docs